name: terraform
on:
  push:
    branches:
    - master
  pull_request:

jobs:
  terraform: 
    runs-on: ubuntu-latest
    steps:
      - name: Configure AWS Credentials Action For GitHub Actions
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.aws_default_region }}
      - name: terraform
        uses: HenriquePiccolo/workflows-reusable/.github/workflows/terraform-workflow.yml@main