name: terraform
on:
  push:
    branches:
    - master
  pull_request:

jobs:
  terraform:
    uses: HenriquePiccolo/workflows-reusable/.github/workflows/terraform-workflow.yml@main
    with:
      aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
      aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      aws-region: ${{ secrets.AWS_DEFAULT_REGION }}
